### ISSUE TITLE
Destroy viewer when component is destroyed

### ISSUE THREAD

**Issue by duebbert** [jarvisniu/vue-pannellum#1]
When a component is destroyed the viewer should also be destroyed otherwise memory keeps building up when using many panoramas.

Using the VueJS hook `beforeDestroy()` this is straight forward:
```
  export default {
      ...
      beforeDestroy() {
         this.viewer.destroy()
      }
      ...
   }
```

**Comment by jarvisniu** [comment]
Many thanks to pointing it out! It has been updated.
