### ISSUE TITLE
360 video in vuejs

### ISSUE THREAD

**Issue by nadavkomo** [jarvisniu/vue-pannellum#12]
Thanx for the amazing tools, how can I use the 360 video with Hot spots in vuejs.

**Comment by jarvisniu** [comment]
I am sorry, this Vue wrap of pannellum does not support the 360 video feature.

It meant to display the panorama more easy in Vue.

But 360 videos is much more complex compared to images. The official [demo page](https://pannellum.org/documentation/examples/video/) implements it by providing a plugin for a 3rd library video js.

So i think i can't and should not integrate it into this library.

I recommend to create another special vue plugin library that wrap video.js + pannellum + video-js-pannellum-plugin to fulfill this need.

Or maybe you can find a 360 video library that has the hot spot feature.
