### ISSUE TITLE
How do I use it in a Vue CLI 3 project?

### ISSUE THREAD

**Issue by Carlos-NBS** [jarvisniu/vue-pannellum#2]
Hello, I'm trying to use it in a Vue CLI 3 project.
I have installed, registered in 'main.js' and used in 'App.vue' following the tutorial but it's doesn't show anything.
I does't know if I'm doing something wrong so I would greatly appreciate your help.

**Comment by jarvisniu** [comment]
I think you might be need to set a height style to your component like:
```html
<v-pennellum :src="equirectangularUrl" style="height: 500px;"/>
```

This is my full code:
```html
```

**Comment by Carlos-NBS** [comment]
Thank you so much, i finally had some time to fixed it

**Comment by chs-zalam** [comment]
@Carlos-NBS how did you fixed that?

**Comment by zeeshanalam39** [comment]
@Carlos-NBS Adding width/height worked for me. I was facing same issue. Add a class on `<v-pannellum class='pannellum '><v-pannellum/>` directive and add following styles:
```
 .pannellum {
    width: 500px;
    height: 500px;
  }
```
