### ISSUE TITLE
CORS: Issue 

### ISSUE THREAD

**Issue by itsKros** [jarvisniu/vue-pannellum#6]
Access to XMLHttpRequest at 'https://subdomain.domain.com/image.jpg' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Why this is happening?

**Comment by jarvisniu** [comment]
Because the server of the image file don't want other websites to use their images.

If it allow, there will be a `Access-Control-Allow-Origin: *` header. e.g. this url: `https://pannellum.org/images/alma.jpg`.

Please have a try.
