### ISSUE TITLE
TypeError: Failed to execute 'readAsBinaryString' on 'FileReader': parameter 1 is not of type 'Blob'

### ISSUE THREAD

**Issue by 531431988** [jarvisniu/vue-pannellum#7]
![image](https://user-images.githubusercontent.com/8703951/77147183-b0795800-6ac7-11ea-897f-af72901dfe07.png)

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/77147520-63e24c80-6ac8-11ea-8073-5b36008feae9.png)

用了官方的一直报这个blob的错误，然后换了这个插件还是报，但clone这个项目正常运行，请教一下什么情况

**Comment by jarvisniu** [comment]
mounted() 下一行：pannellum.viewer() 初始化函数的第一个参数，必须是一个 HTML 元素。
可以是 document.querySelector('#pannellum') 或 this.$el 或 this.$refs.pannellum。

**Comment by jarvisniu** [comment]
你贴的代码好像没有问题，我猜是你的构建工具在处理图片时有问题。
你把 import equirectangularUrl 这行注释掉，改为这个试试。
```js
let equirectangularUrl = 'https://pannellum.org/images/alma.jpg'
```

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/77217284-3f37b480-6b5c-11ea-9a7b-a1724aff408e.png)

我也猜到是这个问题，下面这个图片地址是可以正常访问的，
我用的是VUECLI3创建的，不知道有什么解决方案？

**Comment by jarvisniu** [comment]
我用 Vue CLI 3 新建了一个项目。没有复现你的问题。
我建议你把上面这个图片下载到你有问题的图片旁边，改一下URL，看看是不是这张图片文件本身的问题。

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/77240876-0f54e380-6c26-11ea-94a3-03f662ac60b8.png)
下载了上面的图片，依然如此，新建个项目试一下,确实没发现问题在哪

**Comment by jarvisniu** [comment]
你再看看你的 package.json 里是不是有 `mockjs` 这个依赖，如果有，就是它的问题，需要把它关掉。

如果还不行，就用断点调试在有问题的那行代码那里看看 parameter 1 不是 Blob，到底是个什么，然后什么原因导致它不是Blob。按我之前的经验 mockjs 会导致这个问题。

打断点调试的流程为：1.点pannellum.js?57ec:50  2.点击这行代码最前面的空白，显示出一个红点  3.刷新页面后程序应该会终端在这里  4.光标指向 parameter 1，Tooltip里会说它是什么。
